name: Build Executables

on:
  push:
    branches: [ master ]        # change to your branch name if not 'main'
  workflow_dispatch:           # allows manual trigger

jobs:

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install PyInstaller
      run: pip install pyinstaller PyPDF2

    - name: Build Windows EXE
      run: pyinstaller --onefile --paths=. --collect-submodules dnd_code --hidden-import=PyPDF2 --hidden-import=pygame dnd.py

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: dist/*


  build-mac:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build Mac App
      run: pyinstaller --windowed --paths=. --collect-submodules dnd_code --hidden-import=PyPDF2 --hidden-import=pygame dnd.py

    - name: Upload Mac artifact
      uses: actions/upload-artifact@v4
      with:
        name: mac-build
        path: dist/*
