name: Build Executables

on:
  push:
    branches: [ main ]        # change to your branch name if not 'main'
  workflow_dispatch:           # allows manual trigger

jobs:

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install PyInstaller
      run: pip install pyinstaller PyPDF2

    - name: Build Windows EXE
      run: pyinstaller --onefile --hidden-import=dndcombat --hidden-import=dnd_combat_fn --hidden-import=dnd_tools --hidden-import=dnd_bkg_gen --hidden-import=dnd_bkg_race_sum --hidden-import=dnd_class_expl --hidden-import=dnd_class_gen --hidden-import=dnd_languageskills --hidden-import=dnd_monsters --hidden-import=dnd_npc --hidden-import=dnd_race_gen --hidden-import=dnd_spells --hidden-import=dnd_update --hidden-import=Feats --hidden-import=dnd_python_classes --hidden-import=PyPDF2 --hidden-import=pygame dnd.py

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: dist/*


  build-mac:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build Mac App
      run: pyinstaller --windowed dnd_code/dnd.py

    - name: Upload Mac artifact
      uses: actions/upload-artifact@v4
      with:
        name: mac-build
        path: dist/*