name: Build Executables

on:
  push:
    branches: [ master ]        # change to your branch name if not 'main'
  workflow_dispatch:           # allows manual trigger

jobs:

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install Dependencies
      run: pip install pygame pyinstaller PyPDF2   

    - name: Build Windows EXE
      run: pyinstaller --clean --onefile --collect-all dnd_code --collect-submodules dnd_code --add-data "DnD_5E_CharacterSheet_FormFillable.pdf;." dnd.py

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: DnD_Code_Windows
        path: dist/dnd.exe


  build-mac:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install Dependencies
      run: pip install pygame PyPDF2 pyinstaller

    - name: Build Mac App
      run: pyinstaller --clean --windowed --onefile --collect-all dnd_code --collect-submodules dnd_code --add-data "DnD_5E_CharacterSheet_FormFillable.pdf:." dnd.py

    - name: Upload Mac artifact
      uses: actions/upload-artifact@v4
      with:
        name: DnD_Code_Mac
        path: dist/dnd.app
